# Use an official Python runtime as the base image
FROM python:3.9

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /code

# Install dependencies
COPY requirements.txt /code/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN ls -a


RUN pwd

RUN ls -a

#RUN python manage.py migrate

# Expose the Django development server port (change it if necessary)
CMD ["python", "manage.py", "runserver", "0.0.0.0:80"]
